version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: presensi-app
    container_name: presensi_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - presensi-network

  nginx:
    image: nginx:alpine
    container_name: presensi_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - presensi-network

networks:
  presensi-network:
    driver: bridge
