services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: presensi-app
    container_name: presensi_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
    networks:
      - presensi-network

  nginx:
    image: nginx:alpine
    container_name: presensi_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app-data:/var/www/html
      - ./storage:/var/www/html/storage
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - presensi-network

volumes:
  app-data:

networks:
  presensi-network:
    driver: bridge
